import Head from "next/head";
import Image from "next/image";
import PostForm from "./PostForm";
import Hero from "./Hero";
import PostDisplay from "./PostDisplay";
import Navbar from "./Navbar";
import { useContext } from "react";
import { UserContext } from "../context/userContext";

export default function Home() {
  const { user } = useContext(UserContext);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar user={user} />
      <Hero />
      <PostDisplay />
      <PostForm />
    </>
  );
}
