import Head from "next/head";
import Image from "next/image";
import PostForm from "./PostForm";
import Hero from "./Hero";
import Navbar from "./Navbar";
import { useContext, useEffect } from "react";
import { UserContext } from "../context/UserContext";
import axios from "axios";

export default function Home() {
  const { currentUser } = useContext(UserContext);

  const handleTest = async () => {
    const response = await axios.get("/api/test");
    console.log(response.data);
  };

  return (
    <>
      <Head>
        <title>CSB</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar currentUser={currentUser} />
      <Hero />
      <PostForm />
      <button onClick={handleTest}>test</button>
    </>
  );
}
